name: easyrenamer
description: "A tool to rename and organize your images efficiently"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.4
  desktop_drop: ^0.5.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  file_selector_macos: ^0.9.4+5
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4  # MOVED TO dev_dependencies

flutter_launcher_icons:  # CHANGED FROM flutter_icons
  image_path: "assets/easyrenamer_icon.png"
  android: true
  ios: true
  macos:
    image_path: "assets/easyrenamer_icon.png"
    generate: true
  windows:
    image_path: "assets/easyrenamer_icon.png"
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/